exports.RSI = exports.rsi = require('./rsi')
exports.SMA = exports.sma = require('./sma')
exports.EMA = exports.ema = require('./ema')
exports.BB = exports.bb = require('./bb')
exports.ADX = exports.adx = require('./adx')
exports.MACD = exports.macd = require('./macd')
// exports.ADL = exports.adl = require('./adl') ei jostain syystä toimi, tulos on NaN ???
exports.VWAP = exports.vwap = require('./vwap')
exports.ATR = exports.atr = require('./atr')
exports.FI = exports.fi = require('./fi')
exports.CCI = exports.cci = require('./cci')
